version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "yourusername"  # Replace with your GitHub username
    assignees:
      - "yourusername"  # Replace with your GitHub username
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    
    # Group minor and patch updates together
    groups:
      firebase:
        patterns:
          - "firebase*"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      vite:
        patterns:
          - "vite*"
          - "@vitejs/*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
      typescript:
        patterns:
          - "typescript*"
          - "@types/*"
      ui-components:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "tailwind*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "yourusername"  # Replace with your GitHub username
    assignees:
      - "yourusername"  # Replace with your GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"